name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image - General Server
        working-directory: general-server
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/general-server:latest

      - name: Build Docker image - Remote Repo Server
        working-directory: remote-repo-server
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/remote-repo-server:latest

      - name: Build Docker image - LLM Server
        working-directory: llm-server
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/llm-server:latest

      - name: Build Docker image - Webhook
        working-directory: webhook
        run: docker build . --file Dockerfile --tag ${{ vars.DOCKER_USERNAME }}/webhook:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker images
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/general-server:latest
          docker push ${{ vars.DOCKER_USERNAME }}/remote-repo-server:latest
          docker push ${{ vars.DOCKER_USERNAME }}/llm-server:latest
          docker push ${{ vars.DOCKER_USERNAME }}/webhook:latest
